### ISSUE TITLE
add a current location marker to the app

### ISSUE THREAD

**Issue by MarcusDunn** [VikeLabs/maps#21]
there should be a way for a user to see where they currently are

use this:
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

**Comment by MarcusDunn** [comment]
@OmarMadhani The file you'll want to edit is `Map.svelte` there should be examples of placing and removing markers in there as well.

**Comment by lbare** [comment]
@OmarMadhani I just finished this issue and didn't realize you had been assigned to it, so sorry for that! I'll make sure to get an issue no one is working on next time

**Comment by OmarMadhani** [comment]
@Ibare Oh. No problem. I'll ask Marcus tomorrow to assign me a new issue. 👍

**Comment by MarcusDunn** [comment]
resolved by #50
